"""İlk ilişkisel Mergen veri modeli"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "f95c4e15293b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("original_idea", sa.String(), nullable=False),
        sa.Column("primary_domain", sa.String(), nullable=False),
        sa.Column(
            "secondary_domains",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column(
            "analysis",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "discovery_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "user_skills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("skill_slug", sa.String(), nullable=False),
        sa.Column("knowledge_status", sa.String(), nullable=False),
        sa.Column("self_reported_level", sa.String(), nullable=True),
        sa.Column("assessed_level", sa.Double(), nullable=True),
        sa.Column("last_assessed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_slug"),
    )
    op.create_index(op.f("ix_user_skills_user_id"), "user_skills", ["user_id"], unique=False)
    op.create_table(
        "advisor_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_advisor_messages_project_id"), "advisor_messages", ["project_id"], unique=False)
    op.create_table(
        "roadmap_maps",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("generation_key", sa.String(), nullable=False),
        sa.Column("parent_map_id", sa.String(), nullable=True),
        sa.Column("parent_node_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("generation_status", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_map_id"],
            ["roadmap_maps.id"],
        ),
        *(
            [sa.ForeignKeyConstraint(["parent_node_id"], ["roadmap_nodes.id"], name="fk_map_parent_node")]
            if op.get_bind().dialect.name == "sqlite"
            else []
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_node_id"),
        sa.UniqueConstraint("project_id", "generation_key"),
    )
    op.create_index(op.f("ix_roadmap_maps_project_id"), "roadmap_maps", ["project_id"], unique=False)
    op.create_table(
        "roadmap_nodes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("map_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "skills",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("child_map_id", sa.String(), nullable=True),
        sa.Column("estimated_hours", sa.Double(), nullable=False),
        sa.Column("remediation_for_node_id", sa.String(), nullable=True),
        sa.Column("task_completed", sa.Boolean(), nullable=False),
        sa.Column("task_evidence", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["child_map_id"], ["roadmap_maps.id"], name="fk_node_child_map"),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["roadmap_maps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["remediation_for_node_id"],
            ["roadmap_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("map_id", "key"),
    )
    op.create_index(op.f("ix_roadmap_nodes_map_id"), "roadmap_nodes", ["map_id"], unique=False)
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key(
            "fk_map_parent_node", "roadmap_maps", "roadmap_nodes", ["parent_node_id"], ["id"]
        )
    op.create_table(
        "assessments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("passing_score", sa.Double(), nullable=False),
        sa.Column(
            "questions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["roadmap_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id"),
    )
    op.create_index(op.f("ix_assessments_node_id"), "assessments", ["node_id"], unique=False)
    op.create_table(
        "roadmap_edges",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("map_id", sa.String(), nullable=False),
        sa.Column("source_node_id", sa.String(), nullable=False),
        sa.Column("target_node_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["roadmap_maps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["roadmap_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["roadmap_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("map_id", "source_node_id", "target_node_id", "kind"),
    )
    op.create_index(op.f("ix_roadmap_edges_map_id"), "roadmap_edges", ["map_id"], unique=False)
    op.create_table(
        "assessment_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("assessment_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(), nullable=False),
        sa.Column(
            "answers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column(
            "weak_skills",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_id", "user_id", "submission_id"),
    )
    op.create_index(
        op.f("ix_assessment_attempts_assessment_id"), "assessment_attempts", ["assessment_id"], unique=False
    )
    op.create_index(op.f("ix_assessment_attempts_user_id"), "assessment_attempts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_map_parent_node", "roadmap_maps", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assessment_attempts_user_id"), table_name="assessment_attempts")
    op.drop_index(op.f("ix_assessment_attempts_assessment_id"), table_name="assessment_attempts")
    op.drop_table("assessment_attempts")
    op.drop_index(op.f("ix_roadmap_edges_map_id"), table_name="roadmap_edges")
    op.drop_table("roadmap_edges")
    op.drop_index(op.f("ix_assessments_node_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_roadmap_nodes_map_id"), table_name="roadmap_nodes")
    op.drop_table("roadmap_nodes")
    op.drop_index(op.f("ix_roadmap_maps_project_id"), table_name="roadmap_maps")
    op.drop_table("roadmap_maps")
    op.drop_index(op.f("ix_advisor_messages_project_id"), table_name="advisor_messages")
    op.drop_table("advisor_messages")
    op.drop_index(op.f("ix_user_skills_user_id"), table_name="user_skills")
    op.drop_table("user_skills")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###
